apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20250122.903.42190
spec:
  refName: spring-music.apps.local
  releasedAt: "2025-01-22T09:05:29Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ttl.sh/tpapps/containerapp-spring-music@sha256:0449cc647c243d9b996c3d30a8158d1b8d8e864902d35843fe6a948e76e64c9b
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250122.903.42190
